### PR TITLE
Add Hungarian localization

### PR DESCRIPTION
**Pull request by fejese**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Do you know anyone that could review your translations?

**Comment by fejese** [comment]
Maybe @waydabber? I made this PR based on their recommendation in https://github.com/MonitorControl/MonitorControl/discussions/637#discussion-3602653 :)

**Review by waydabber — COMMENTED** [review]
Hi @fejese, I'd change all occurrences of `rendszer szintü` to `rendszerszintű`... for grammar's sake! ;)

Thank you!

**Comment by fejese** [comment]
@waydabber, nice catch! Will update the PR

Thanks

**Comment by fejese** [comment]
Typo fixed

**Pull request merged**
