### PR TITLE
Fix compatibility with `View#focused()`

### LINKED ISSUE #76: can't focus on KeyboardShortcuts Recorder input
```swift
...
@FocusState private var shouldRecordCustomShortcut: Bool
...
.onChange(of: enterNormalModeWith) { _ in
    shouldRecordCustomShortcut = true
}
...
KeyboardShortcuts.Recorder(for: .enterNormalMode).focused($shouldRecordCustomShortcut)
```

i would expect the `KeyboardShortcuts Recorder` to be focused and being able to type a shortcut to be recorded. but although the code removes the focus from any other field, the `KeyboardShortcuts Recorder` doesn't get focused.

if i replace the `KeyboardShortcuts Recorder` by any other field, it works. so my code itself seems to be fine.

any more info i could give to help? thanks.

### PR DESCRIPTION
**Pull request by sindresorhus**
Fixes #76

@godbout The problem was that the recorder needs to prevent initial focus, otherwise it would enter the key recording when the window shows. I previously solved this by preventing it from becoming a key view. That's what prevented focus.

I'm not really happy with what's in this pull request, but it's the best I could come up with. I'm open to other ideas. I'm also concerned it may break some usage, although it worked fine in the example app and my Dato app.

You also need a dispatch call on before setting the focus. I think that's a SwiftUI bug and unrelated to this.

Could you try out this pull request in your app?

### CODE REVIEW

**Comment by godbout** [comment]
ah! thank you. and thanks for the explanation, always eager to know what's going on. no worries about the SwiftUI bug, i've been dealing with those for the past 2 years 😅️ i know the pain.

i'll pull tomorrow or the day after and will keep you updated.

**Comment by godbout** [comment]
https://user-images.githubusercontent.com/121373/166643382-5f9e23c3-1868-4103-95e4-c11276d5edd4.mp4

works beautifully man, thanks. using the dispatch call on my Picker, the focus for the `sequence` works fine too, so no side effect. seems very good to me.

**Comment by godbout** [comment]
> I'm not really happy with what's in this pull request, but it's the best I could come up with. I'm open to other ideas.

wish i could help but currently absolutely no time to dig into this, sorry.

> I'm also concerned it may break some usage, although it worked fine in the example app and my Dato app.

as far as i'm concerned, it's 👍️
up to you to decide if it's ok to merge it or not, but if you do i'll take it!

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/KeyboardShortcuts/releases/tag/v1.7.0

You do not need the `DispatchQueue.main.async` call anymore.

**Comment by godbout** [comment]
thank you!

**Comment by godbout** [comment]
> You do not need the `DispatchQueue.main.async` call anymore.

FWIW in my case i still need the Dispatch else it fails sometimes.

**Comment by godbout** [comment]
with Dispatch:

https://user-images.githubusercontent.com/121373/172125995-1927aa4a-07db-44b2-8b28-53860344d574.mp4

without Dispatch:

https://user-images.githubusercontent.com/121373/172126126-ab900172-bfdb-4b89-b555-0fe9cb006f6d.mp4

using the Dispatch makes it work all good for me, so no worries. thank you!

**Comment by sindresorhus** [comment]
Then it might be an issue with SwiftUI. There are some issues with focus. I cannot reproduce it with the example app.

**Comment by godbout** [comment]
no worries. i might be doing something wrong on my side. not very SwiftUI-proficient here. (although the focus is quite straightforward.)

**Pull request merged**
