### PR TITLE
Pause keyboard shortcut events while a recorder input is active

### LINKED ISSUE #20: Disable all shortcuts and then re-enable them
There should be a way to disable all shortcuts and then re-enable them. This is useful on a Preferences screen where you are registering a bunch of shortcuts. While you are entering new shortcuts, you should not be able to invoke the global shortcuts, especially when the control has focus. 

Currently there is no way to disable global hotkey monitoring.

### PR DESCRIPTION
**Pull request by sindresorhus**
Fixes #20

### CODE REVIEW

**Comment by sindresorhus** [comment]
@pavanpodila Can you try this PR in your app and see if it fixes the problem for you? You shouldn't have to do any code changes.

**Comment by pavanpodila** [comment]
I'm using via SPM. Is there a temp version you can publish ?

**Comment by sindresorhus** [comment]
SPM supports targeting branches and commits.

**Comment by pavanpodila** [comment]
Ok, after switching to the recorder-pause branch, I am getting this strange error on using `Key.one` ?
```
(17, 67) 'one' is inaccessible due to 'internal' protection level
```

**Comment by pavanpodila** [comment]
I think you may need to mark the extension on `KeyboardShortcuts.Key` as **`public`** ?

**Comment by sindresorhus** [comment]
That will be fixed by the other open PR. Try this branch https://github.com/sindresorhus/KeyboardShortcuts/tree/rec which contains both PRs.

**Comment by pavanpodila** [comment]
The rec branch seems to work well. When active, it correctly disables existing shortcuts 👍

**Comment by sindresorhus** [comment]
Thanks for testing 👍🏻

**Comment by pavanpodila** [comment]
Thanks for fixing this! Is there going to be a new release ?

**Comment by sindresorhus** [comment]
When the other open PR is merged. But as you already know, you can target a specific commit if you need it right away.

**Pull request merged**
