### PR TITLE
Add Spanish localization

### PR DESCRIPTION
**Pull request by kant**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Do you know anyone that would be able to review you translation?

**Comment by kant** [comment]
@alesanchezr

**Comment by zydeico** [comment]
The Spanish localization are correct :) I can do the review

**Review by zydeico — APPROVED** [review]

**Comment by kant** [comment]
Thanks, @sindresorhus @zydeico for the support. Best karma for all!

**Comment by sindresorhus** [comment]
The `sp` language code is not correct. It's either `es` (most common) or `spa`.

**Comment by kant** [comment]
@sindresorhus According ISO 639-2 "[Codes for the Representation of Names of Languages](https://www.loc.gov/standards/iso639-2/php/English_list.php)" you are in the right path. Please modify my contribution to your liking

**Comment by kant** [comment]
@sindresorhus According ISO 639-2 "[Codes for the Representation of Names of Languages](https://www.loc.gov/standards/iso639-2/php/English_list.php)" you are in the right path. Please modify my contribution to your liking.

**Comment by sindresorhus** [comment]
I cannot easily change it. It should be `es`.

**Pull request merged**
